export const API_FOOTBALL_RESOURCES = [
  {
    id: "timezones",
    label: "Timezones",
    path: "/timezone",
    parents: [],
    needs: [],
    coverage: null,
    cadence: "weekly",
  },
  {
    id: "seasons",
    label: "Seasons",
    path: "/leagues/seasons",
    parents: [],
    needs: [],
    coverage: null,
    cadence: "weekly",
  },
  {
    id: "countries",
    label: "Countries",
    path: "/countries",
    parents: [],
    needs: [],
    coverage: null,
    cadence: "weekly",
  },
  {
    id: "leagues",
    label: "Leagues",
    path: "/leagues",
    parents: ["seasons", "countries"],
    needs: ["season", "country"],
    coverage: null,
    cadence: "daily",
  },
  {
    id: "venues",
    label: "Venues",
    path: "/venues",
    parents: ["countries", "leagues"],
    needs: ["country"],
    coverage: null,
    cadence: "daily",
  },
  {
    id: "teams",
    label: "Teams",
    path: "/teams",
    parents: ["countries", "leagues"],
    needs: ["league", "season"],
    coverage: null,
    cadence: "daily",
  },
  {
    id: "teamStatistics",
    label: "Teams Statistics",
    path: "/teams/statistics",
    parents: ["teams", "leagues"],
    needs: ["team", "league", "season"],
    coverage: null,
    cadence: "twice-daily",
  },
  {
    id: "standings",
    label: "Standings",
    path: "/standings",
    parents: ["leagues"],
    needs: ["league", "season"],
    coverage: "standings",
    cadence: "hourly",
  },
  {
    id: "topScorers",
    label: "Top Scorers",
    path: "/players/topscorers",
    parents: ["leagues"],
    needs: ["league", "season"],
    coverage: "top_scorers",
    cadence: "hourly",
  },
  {
    id: "players",
    label: "Players",
    path: "/players",
    parents: ["leagues", "teams"],
    needs: ["league", "season"],
    coverage: "players",
    cadence: "daily",
  },
  {
    id: "playerStatistics",
    label: "Players Statistics",
    path: "/players",
    parents: ["players"],
    needs: ["id", "season"],
    coverage: "players",
    cadence: "daily",
  },
  {
    id: "playerSquads",
    label: "Players Squads",
    path: "/players/squads",
    parents: ["teams", "players"],
    needs: ["team"],
    coverage: null,
    cadence: "daily",
  },
  {
    id: "playerProfiles",
    label: "Players Profiles",
    path: "/players/profiles",
    parents: ["players"],
    needs: ["player"],
    coverage: null,
    cadence: "daily",
  },
  {
    id: "playerTeams",
    label: "Players Teams",
    path: "/players/teams",
    parents: ["players"],
    needs: ["player"],
    coverage: null,
    cadence: "daily",
  },
  {
    id: "fixtures",
    label: "Fixtures",
    path: "/fixtures",
    parents: ["leagues"],
    needs: ["league", "season"],
    coverage: null,
    cadence: "daily",
  },
  {
    id: "live",
    label: "Live",
    path: "/fixtures",
    parents: ["fixtures"],
    needs: ["live"],
    coverage: null,
    cadence: "live",
  },
  {
    id: "h2h",
    label: "H2H",
    path: "/fixtures/headtohead",
    parents: ["fixtures", "teams"],
    needs: ["h2h"],
    coverage: null,
    cadence: "on-demand",
  },
  {
    id: "events",
    label: "Events",
    path: "/fixtures/events",
    parents: ["fixtures"],
    needs: ["fixture"],
    coverage: "fixtures.events",
    cadence: "live",
  },
  {
    id: "lineups",
    label: "Lineups",
    path: "/fixtures/lineups",
    parents: ["fixtures"],
    needs: ["fixture"],
    coverage: "fixtures.lineups",
    cadence: "pre-match",
  },
  {
    id: "fixtureStatistics",
    label: "Fixtures Statistics",
    path: "/fixtures/statistics",
    parents: ["fixtures"],
    needs: ["fixture"],
    coverage: "fixtures.statistics_fixtures",
    cadence: "per-minute",
  },
  {
    id: "predictions",
    label: "Predictions",
    path: "/predictions",
    parents: ["fixtures"],
    needs: ["fixture"],
    coverage: "predictions",
    cadence: "hourly",
  },
  {
    id: "injuries",
    label: "Injuries",
    path: "/injuries",
    parents: ["fixtures", "leagues"],
    needs: ["fixture"],
    coverage: "injuries",
    cadence: "every-4-hours",
  },
  {
    id: "odds",
    label: "Odds",
    path: "/odds",
    parents: ["leagues", "fixtures"],
    needs: ["league", "season"],
    coverage: "odds",
    cadence: "every-3-hours",
  },
  {
    id: "preMatchOdds",
    label: "Pre-matches Odds",
    path: "/odds",
    parents: ["odds"],
    needs: ["fixture"],
    coverage: "odds",
    cadence: "every-3-hours",
  },
  {
    id: "liveOdds",
    label: "Live Odds",
    path: "/odds/live",
    parents: ["odds"],
    needs: [],
    coverage: "odds",
    cadence: "live",
  },
  {
    id: "bets",
    label: "Bets",
    path: "/odds/bets",
    parents: ["odds"],
    needs: [],
    coverage: null,
    cadence: "weekly",
  },
  {
    id: "bookmakers",
    label: "Bookmakers",
    path: "/odds/bookmakers",
    parents: ["odds"],
    needs: [],
    coverage: null,
    cadence: "weekly",
  },
  {
    id: "transfers",
    label: "Transfers",
    path: "/transfers",
    parents: ["teams", "players"],
    needs: ["team"],
    coverage: null,
    cadence: "daily",
  },
  {
    id: "coaches",
    label: "Coaches",
    path: "/coachs",
    parents: ["teams"],
    needs: ["team"],
    coverage: null,
    cadence: "daily",
  },
  {
    id: "trophies",
    label: "Trophies",
    path: "/trophies",
    parents: ["players", "coaches"],
    needs: ["player"],
    coverage: null,
    cadence: "daily",
  },
  {
    id: "sidelined",
    label: "Sidelined",
    path: "/sidelined",
    parents: ["players", "coaches"],
    needs: ["player"],
    coverage: null,
    cadence: "daily",
  },
] as const;

export type ApiFootballResource = (typeof API_FOOTBALL_RESOURCES)[number];
export type ApiFootballResourceId = ApiFootballResource["id"];

export const API_FOOTBALL_INGEST_LAYERS = [
  {
    layer: 0,
    purpose: "Reference IDs used by every later call",
    ids: ["timezones", "seasons", "countries"] as const,
  },
  {
    layer: 1,
    purpose: "Competitions for a season and country",
    ids: ["leagues"] as const,
  },
  {
    layer: 2,
    purpose: "League-scoped catalogs and tables",
    ids: [
      "venues",
      "teams",
      "standings",
      "topScorers",
      "players",
      "fixtures",
      "odds",
    ] as const,
  },
  {
    layer: 3,
    purpose: "Records that need a team, player, or fixture ID",
    ids: [
      "teamStatistics",
      "playerSquads",
      "playerStatistics",
      "playerProfiles",
      "playerTeams",
      "transfers",
      "coaches",
      "h2h",
      "live",
      "bets",
      "bookmakers",
    ] as const,
  },
  {
    layer: 4,
    purpose: "Match detail hanging off a fixture ID",
    ids: [
      "events",
      "lineups",
      "fixtureStatistics",
      "predictions",
      "injuries",
      "preMatchOdds",
      "liveOdds",
    ] as const,
  },
  {
    layer: 5,
    purpose: "Career records for a player or coach ID",
    ids: ["trophies", "sidelined"] as const,
  },
] as const;

const resourceById = Object.fromEntries(
  API_FOOTBALL_RESOURCES.map((resource) => [resource.id, resource]),
) as Record<ApiFootballResourceId, ApiFootballResource>;

export function getApiFootballResource(id: ApiFootballResourceId) {
  return resourceById[id];
}

export function getApiFootballChildren(id: ApiFootballResourceId) {
  return API_FOOTBALL_RESOURCES.filter((resource) =>
    (resource.parents as readonly ApiFootballResourceId[]).includes(id),
  );
}
